language: php

php:
  - 7.0

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction --ignore-platform-reqs
  - php artisan key:generate
  - php artisan migrate:refresh
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install --global gulp-cli
  - npm install
  - npm run prod

before_install:
  - psql -c "CREATE DATABASE postgres;" -U postgres
  - psql -c "CREATE USER homestead WITH PASSWORD 'secret';" -U postgres
  
script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
  
services:
  - postgresql

cache:
  directories:
    - node_modules
    - vendor
    
env:
  - TRAVIS_NODE_VERSION="4"