sudo: required
dist: trusty
language: php

php:
  - '7.0'

services:
  - postgresql

before_install:
  - psql -c "CREATE USER homestead WITH PASSWORD 'secret';" -U postgres
  - psql -c "CREATE SCHEMA esport_test;" -U postgres
  - psql -c "GRANT ALL ON SCHEMA esport_test TO homestead;" -U postgres

install:
   - cp .env.travis .env
   - composer self-update
   - composer install --no-interaction --ignore-platform-reqs --no-suggest
   - php artisan key:generate
   - php artisan migrate:refresh
   - rm -rf node_modules
   - npm install 
   - npm rebuild node-sass

before_script:
   #- export DISPLAY=:0 
   #- sh -e /etc/init.d/xvfb start
   - ./vendor/laravel/dusk/bin/chromedriver-linux &
   - php artisan serve &

script:
   #- npm run prod
   - npm run dev
   - composer dump-autoload
   - mkdir -p build/logs
   - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
   - php artisan dusk

after_script:
   - php vendor/bin/coveralls -v

after_success:
   - travis_retry php vendor/bin/coveralls

cache:
  directories:
    - node_modules
    - vendor
    
env:
  - TRAVIS_NODE_VERSION="4"