language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction --ignore-platform-reqs
  - php artisan key:generate
  - php artisan migrate:refresh
  - rm -rf node_modules
  - npm install 
  - npm rebuild node-sass

before_install:
  - psql -c "CREATE USER homestead WITH PASSWORD 'secret';" -U postgres
  - psql -c "CREATE SCHEMA esport_test;" -U postgres
  - psql -c "GRANT ALL ON SCHEMA esport_test TO homestead;" -U postgres
  
script:
  - npm run prod
  - ls
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

after_success:
  - travis_retry php vendor/bin/coveralls

services:
  - postgresql

cache:
  directories:
    - node_modules
    - vendor
    
env:
  - TRAVIS_NODE_VERSION="4"