sudo: required
dist: trusty
language: php

php:
  - '7.0'

addons:
   chrome: stable

install:
   - cp .env.travis .env
   - composer self-update
   - composer install --no-interaction --ignore-platform-reqs --no-suggest

before_script:
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
   - php artisan serve &

script:
   - php artisan dusk